Platzigram/urls.py
from django.contrib import admin
from django.urls import path, include
from Platzigram import views as central_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('hello-world/', central_views.hello_world, name="hello_world"),
    path('sort/', central_views.sort, name="sort_numbers"),
    path('greet/<str:name>/<int:age>/', central_views.greet, name="greet"),
    
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts app URL Configuration"""

from django.urls import path

from . import views

urlpatterns = [
    path('', views.PostsFeedView.as_view(), name='feed'),
    path('posts/create/', views.CreatePostView.as_view(), name='create'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='details'),
]

users/urls.py
"""Users app URL Configuration"""

from django.urls import path

from . import views

urlpatterns = [

    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('me/profile/', views.UpdateProfileView.as_view(), name="update"),
    
    path(
        route = '<str:username>/',
        view = views.UserDetailView.as_view(),
        name = 'details'
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% block head_content %}
	{% endblock %}

	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	<link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous" defer></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous" defer></script>
</head>
<body>
	{% include "nav.html" %}
	<div class="container mt-5">
		{% block content %}
		{% endblock %}
	</div>
</body>

</html>

templates/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
	<div class="container">
		<a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
			<img src="{% static 'img/instagram.png' %}" height="35" class="d-inline-block align-top"/>
		</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigationLinks" >
      <span class="navbar-toggler-icon"></span>
    </button>
		<div class="collapse navbar-collapse" id="navigationLinks">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a href="{% url 'users:details' request.user.username %}">
            {% if request.user.profile.profile_picture %}
              <img src="{{ request.user.profile.profile_picture.url }}" width ="35" height="35"
                   class="d-inline-block align-top rounded-circle"/>
            {% else%}
              <img src="{% static 'img/default-profile.png' %}" height="35"
                   class="d-inline-block align-top rounded-circle"/>
            {% endif %}
					</a>
				</li>
				<li class="nav-item nav-icon">
					<a href="{% url 'posts:create' %}">
						<i class="fas fa-plus"></i>
					</a>
				</li>
				<li class="nav-item nav-icon">
					<a href="{% url 'users:logout' %}">
						<i class="fas fa-sign-out-alt"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>