Platzigram/urls.py
from django.contrib import admin
from django.urls import path, include
from Platzigram import views as central_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('hello-world/', central_views.hello_world, name="hello_world"),
    path('sort/', central_views.sort, name="sort_numbers"),
    path('greet/<str:name>/<int:age>/', central_views.greet, name="greet"),
    
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts app URL Configuration"""

from django.urls import path

from . import views

urlpatterns = [
    path('', views.PostsFeedView.as_view(), name='feed'),
    path('posts/create/', views.CreatePostView.as_view(), name='create'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='details'),
]

users/urls.py
"""Users app URL Configuration"""

from django.urls import path

from . import views

urlpatterns = [

    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('me/profile/', views.UpdateProfileView.as_view(), name="update"),
    
    path(
        route = '<str:username>/',
        view = views.UserDetailView.as_view(),
        name = 'details'
    ),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

 
class Profile(models.Model):
    """ Representa el perfil de un usuario. Se relaciona 1-1 con la clase User que provee django """
    # Relacion 1-1:
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    web_site = models.CharField(max_length=150, blank=True)
    bio = models.TextField(blank=True)
    birth_date = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True)
    date_modified = models.DateTimeField(auto_now=True)

    profile_picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)

    def __str__(self):
        """Representacion string, retorna username."""
        return self.user.username

users/forms.py
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(max_length=70)
    password_confirm = forms.CharField(max_length=70)

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirm = data['password_confirm']

        if password != password_confirm:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirm')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

class ProfileForm(forms.Form):
    """ Profile update form """
    web_site = forms.CharField(max_length=200, required=True)
    bio = forms.CharField(max_length=500, required=False)
    phone = forms.CharField(max_length=20, required=False)
    profile_picture = forms.ImageField()

    def save(self, profile):
       
        data = self.cleaned_data

        profile.web_site = data['web_site']
        profile.bio = data['bio']
        profile.phone = data['phone']
        profile.profile_picture = data['profile_picture']
        profile.save()

# Profile update form con ModelForm
# class UpdateForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['web_site', 'bio', 'birth_date', 'phone', 'profile_picture',]

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, FormView
from django.views.generic.edit import UpdateView
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy

from django.contrib.auth.models import User
from users.models import Profile
from posts.models import Post

from .forms import ProfileForm, SignupForm


class SignupView(FormView):
    """View sign up"""
    
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class LoginView(auth_views.LoginView):
    """View login"""
                
    template_name = 'users/login.html'


@login_required
def logout_view(request):
    """View logout"""
    logout(request)
    return redirect('users:login')


class UpdateProfileView(LoginRequiredMixin, FormView):
    """View para actualizar datos del perfil"""

    form_class = ProfileForm
    template_name = 'users/update_profile.html'

    def form_valid(self, form):
        
        user = self.request.user
        profile = user.profile

        form.save(profile)

        return super().form_valid(form)

    def get_success_url(self):
        usrname = self.request.user.username
        url = reverse_lazy('users:details', kwargs={'username': usrname})
        return url
                  
class UserDetailView(LoginRequiredMixin, DetailView):
    """View para detalles del usuario."""
    template_name = 'users/details.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'
    
    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        
        return context

templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% block head_content %}
	{% endblock %}

	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	<link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous" defer></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous" defer></script>
</head>
<body class="h-100">
	<div class="container h-100">
		<div class="row h-100 justify-content-center align-items-center">
			<div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
				<img src="{% static 'img/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4"
					style="max-width: 60%;" />
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>
</body>

</html>

templates/users/details.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
	<title>@{{ user.username }} | Profile posts</title>
	<meta name="description" content="Profile posts">
	<meta name="author" content="">
{% endblock %}

{% block content %}
<div class="container mb-5" style="margin-top: 8em;">
  <div class="row">
    <div class="col-sm-4 d-flex justify-content-center">
    {% if request.user.profile.profile_picture %}
      <img  src="{{ user.profile.profile_picture.url }}"
            alt="@{{ user.username}}"
            class="rounded-circle"
            width="150px"
            height="150px"
      />
    {% else%}
      <img  src="{% static 'img/default-profile.png' %}"
            alt="@{{ user.username }}"
            class="rounded-circle"
            width="150px"
            height="150px"
      />
    {% endif %}
        
    </div>

    <div class="col-sm-8">
        <h2 style="font-weight: 100;">
          {{ user.username }}
          {% if user == request.user %}
            <a
              href="{% url 'users:update' %}"
              class="ml-5 btn btn-sm btn-outline-info"
            >
              Edit profile
            </a>
          {% else %}
            <a
              href=""
              class="ml-5 btn btn-sm btn-primary"
            >
              Follow
            </a>
          {% endif %}
        </h2>

        <div class="row mt-2" style="font-size: 1.2em">
            <div class="col-sm-4">
              <b>{{ user.profile.posts_count }}785</b> posts
            </div>
            <div class="col-sm-4">
              <b>{{ user.profile.followers }}1,401</b> followers
            </div>
            <div class="col-sm-4">
              <b>{{ user.profile.following }}491</b> following
            </div>
        </div>
        <div class="row mt-4">
          <div class="col-sm-12">
            <p>{{ user.profile.bio }}</p>
          </div>
        </div>
      </div>
  </div>
</div>

  <hr>

  <div class="container" id="user-posts">
    <div class="row mt-3">
        {% for post in posts %}
        <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
          <a href="" class="border">
            <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
          </a>
        </div>
        {% endfor %}
    </div>
  </div>
{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
	<title>Platzigram Login</title>
	<meta name="description" content="Platzigram Login">
	<meta name="author" content="">
{% endblock %}

{% block content %}
	{% if form.errors %}
		<p class="alert alert-danger">Usuario o contraseña incorrectos.</p>
	{% endif %}
	<form method="POST" action="{% url 'users:login' %}">
		{% csrf_token %}
		<div class="form-group">
			<input class="form-control" type="text" placeholder="Username" name="username" />
		</div>
		<div class="form-group">
			<input class="form-control" type="password" placeholder="Password" name="password" />
		</div>
		<button class="btn btn-primary btn-block mt-5" type="submit">Log in</button>
	</form>
	<p class="mt-4">Don't have an account yet?
		<a href="{% url 'users:signup' %}">Sign up here.</a>
	</p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
	<title>Platzigram Sign Up</title>
	<meta name="description" content="Platzigram Sign Up">
	<meta name="author" content="">
{% endblock %}

{% block content %}
	<form method="POST" action="{% url 'users:signup' %}">
		{% csrf_token %}
	 	<div class="form-group">
			<input class="form-control" type="text" placeholder="Username" name="username" required="true"/>
		</div>
		<div class="form-group">
			<input class="form-control" type="password" placeholder="Password" name="password" required="true" />
		</div>
		<div class="form-group">
			<input class="form-control" type="password" placeholder="Password confirmation" name="password_confirm" required="true" />
		</div>
		<div class="form-group">
			<input class="form-control" type="text" placeholder="First name" name="first_name" required="true" />
		</div>
		<div class="form-group">
			<input class="form-control" type="text" placeholder="Last name" name="last_name" required="true" />
		</div>
		<div class="form-group">
			<input class="form-control" type="e-mail" placeholder="E-mail" name="email" required="true" />
		</div>
		<button class="btn btn-primary btn-block mt-5" type="submit">Sign Up</button>
	</form>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
	<title>@{{ user.username }} | Update profile</title>
	<meta name="description" content="Update profile">
	<meta name="author" content="">
{% endblock %}

{% block content %}
<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.profile_picture %}
                        <img src="{{ profile.profile_picture.url }}" class="rounded-circle" height="50" />
                    {% else %}
						 <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
					{% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="profile_picture" /></p>
                    </div>
                </div>

                {% for error in form.profile_picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{ error }}
                </div>
                {% endfor %}

                <hr><br>

                {# Website field #}
                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.web_site.errors %}is-invalid{% endif %}"
                        type="text"
                        name="web_site"
                        placeholder="Website"
                        value="{% if form.errors %}{{ form.web_site.value }}{% else %}{{ profile.web_site }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.web_site.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                {# Bio field #}
                <div class="form-group">
                    <label>Bio</label>
                    <textarea class="form-control {% if form.bio.errors %}is-invalid{% endif %}" name="bio">
                        {% if form.errors %}{{ form.bio.value }}{% else %}{{ profile.bio }}{% endif %}
                    </textarea>
                    <div class="invalid-feedback">
                        {% for error in form.bio.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Phone number field #}
                <div class="form-group">
                    <label>Phone</label>
                    <input
                        class="form-control {% if form.phone.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone"
                        placeholder="Phone"
                        value="{% if form.errors %}{{ form.phone.value }}{% else %}{{ profile.phone }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update profile</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}